### ISSUE TITLE
Numpy version issue

### ISSUE THREAD

**Issue by utahboy3502** [sp-uhh/ears_benchmark#1]
I have encountered issue when I followed the following the command:

python3 generate_ears_reverb.py --data_dir <data_dir> --copy_clean

![CleanShot 2024-06-28 at 11 20 19](https://github.com/sp-uhh/ears_benchmark/assets/82129086/5609e7d9-703e-4be6-a2f5-6f5f1a08435b)

It seems that Numpy has been recently upgraded to 2.0.0 as the latest version.
And Numpy==2.0.0 is not compatible with the submodules inside of the script files.

So, after downgrading to Numpy to 1.26.4 version, now it is working fine. 

So, anyone experiencing the same issue as I did, you can follow me.

**Comment by julius-richter** [comment]
Thanks for letting us know. We have set `numpy<2.0` as a requirement in the latest commit.
