### ISSUE TITLE
question about the si-sdr in ears-wham dataset

### ISSUE THREAD

**Issue by ioyy900205** [sp-uhh/ears_benchmark#2]
I encountered a discrepancy while calculating the SISDR metric on the ears-wham dataset. The SISDR value I computed is 5.85, whereas the paper reports a value of 5.98. However, the PESQ and eSTOI results seem to match. Please review my detailed log in the attached CSV file. Below is the code I used for calculating the SISNR.

[noisy_metric.csv](https://github.com/user-attachments/files/16061291/noisy_metric.csv)

```python
def sisnr(est, label):
    label_power = np.sum(label**2.0) + 1e-8
    scale = np.sum(est*label) / label_power
    est_true = scale * label
    est_res = est - est_true
    true_power = np.sum(est_true**2.0, axis=0) + 1e-8
    res_power = np.sum(est_res**2.0, axis=0) + 1e-8
    sdr = 10*np.log10(true_power) - 10*np.log10(res_power)
    return sdr```

**Comment by julius-richter** [comment]
We took the code from [here](https://github.com/fgnt/pb_bss/blob/master/pb_bss/evaluation/module_si_sdr.py) to calculate SI-SDR. It seems that the code does not use an eps value of 1e-8 as you do.

Please evaluate the data again and let me know if there are any differences.
